spring:
  application:
    name: spring-batch-processing-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/spring-batch-db?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  batch:
    initialize-schema: ALWAYS
    #diabled job run at startup
    job:
      enabled: false

